library(tidyverse)

dat <- read.csv("POL-3015/data/sondage_raw.csv", sep = ";")

#### Recode ####
summary(dat)

dat <- dat %>% 
  mutate(securite_immigration = NA, # question retirée ex-post
         influence_medias = NA, # question retirée ex-post
         sophistication_etatsunis = ifelse(sophistication_etatsunis == 2, 1, 0),
         sophistication_freeland = ifelse(sophistication_freeland == 5, 1, 0),
         sophistication_legault = ifelse(sophistication_legault == 4, 1, 0),
         sophistication_macron = ifelse(sophistication_macron == 2, 1, 0),
         sophistication_pence = ifelse(sophistication_pence == 3, 1, 0),
         sophistication_singh = ifelse(sophistication_singh == 1, 1, 0),
         vote_quebec2018_CAQ = ifelse(quebec_2018 == 1, 1, 0),
         vote_quebec2018_PQ = ifelse(quebec_2018 == 2, 1, 0),
         vote_quebec2018_PLQ = ifelse(quebec_2018 == 3, 1, 0),
         vote_quebec2018_QS = ifelse(quebec_2018 == 4, 1, 0),
         vote_quebec2018_vert = ifelse(quebec_2018 == 5, 1, 0),
         vote_quebec2018_autre = ifelse(quebec_2018 == 6, 1, 0),
         vote_quebec2018_bulletinnul = ifelse(quebec_2018 == 7, 1, 0),
         vote_quebec2018_pasvote = ifelse(quebec_2018 == 8, 1, 0),
         vote_france_enmarche = ifelse(vote_france == 1, 1, 0),
         vote_france_republicains = ifelse(vote_france == 2, 1, 0),
         vote_france_verts = ifelse(vote_france == 3, 1, 0),
         vote_france_PS = ifelse(vote_france == 4, 1, 0),
         vote_france_RN = ifelse(vote_france == 5, 1, 0),
         vote_france_insoumise = ifelse(vote_france == 6, 1, 0),
         vote_canada_liberal = ifelse(vote_canada == 1, 1, 0),
         vote_canada_conservateur = ifelse(vote_canada == 2, 1, 0),
         vote_canada_npd = ifelse(vote_canada == 3, 1, 0),
         vote_canada_bloc = ifelse(vote_canada == 4, 1, 0),
         vote_canada_vert = ifelse(vote_canada == 5, 1, 0),
         vote_canada_autre = ifelse(vote_canada == 6, 1, 0),
         vote_quebec_CAQ = ifelse(vote_quebec == 1, 1, 0),
         vote_quebec_PQ = ifelse(vote_quebec == 2, 1, 0),
         vote_quebec_PLQ = ifelse(vote_quebec == 3, 1, 0),
         vote_quebec_QS = ifelse(vote_quebec == 4, 1, 0),
         vote_quebec_vert = ifelse(vote_quebec == 5, 1, 0),
         vote_quebec_autre = ifelse(vote_quebec == 6, 1, 0),
         ideologie_VD = ideologie, # ajouter VD
         vote_nationaliste_VD  = vote_nationaliste,
         participation_VD  = participation,
         vote_quebec2018_CAQ_VD  = vote_quebec2018_CAQ,
         vote_quebec2018_PQ_VD  = vote_quebec2018_PQ,
         vote_quebec2018_PLQ_VD = vote_quebec2018_PLQ,
         vote_quebec2018_QS_VD  = vote_quebec2018_QS,
         vote_quebec2018_vert_VD  = vote_quebec2018_vert,
         vote_quebec2018_autre_VD  = vote_quebec2018_autre,
         vote_quebec2018_bulletinnul_VD  = vote_quebec2018_bulletinnul,
         vote_quebec2018_pasvote_VD  = vote_quebec2018_pasvote,
         vote_US_VD  = vote_US,
         vote_france_enmarche_VD  = vote_france_enmarche,
         vote_france_republicains_VD  = vote_france_republicains,
         vote_france_verts_VD  = vote_france_verts,
         vote_france_PS_VD  = vote_france_PS,
         vote_france_RN_VD  = vote_france_RN,
         vote_france_insoumise_VD  = vote_france_insoumise,
         vote_canada_liberal_VD  = vote_canada_liberal,
         vote_canada_conservateur_VD  = vote_canada_conservateur,
         vote_canada_npd_VD  = vote_canada_npd,
         vote_canada_bloc_VD = vote_canada_bloc,
         vote_canada_vert_VD  = vote_canada_vert,
         vote_canada_autre_VD  = vote_canada_autre,
         vote_quebec_CAQ_VD  = vote_quebec_CAQ,
         vote_quebec_PQ_VD  = vote_quebec_PQ,
         vote_quebec_PLQ_VD  = vote_quebec_PLQ,
         vote_quebec_QS_VD  = vote_quebec_QS,
         vote_quebec_vert_VD  = vote_quebec_vert,
         vote_quebec_autre_VD = vote_quebec_autre,
         anciens_presidents_VD = anciens_presidents,
         vote_strategique_VD = vote_strategique,
         changement_scrutin_VD = ifelse(changement_scrutin < 6, changement_scrutin, NA))

table(dat$securite_immigration)
table(dat$influence_medias)
table(dat$vote_nationaliste)
table(dat$vote_strategique)

table(dat$sophistication_etatsunis)
table(dat$sophistication_freeland)
table(dat$sophistication_legault)
table(dat$sophistication_macron)
table(dat$sophistication_pence)
table(dat$sophistication_singh)

table(dat$quebec_2018, dat$vote_quebec2018_CAQ)
table(dat$quebec_2018, dat$vote_quebec2018_PQ)
table(dat$quebec_2018, dat$vote_quebec2018_PLQ)
table(dat$quebec_2018, dat$vote_quebec2018_QS)
table(dat$quebec_2018, dat$vote_quebec2018_vert)
table(dat$quebec_2018, dat$vote_quebec2018_autre)
table(dat$quebec_2018, dat$vote_quebec2018_bulletinnul)
table(dat$quebec_2018, dat$vote_quebec2018_pasvote)

table(dat$vote_quebec, dat$vote_quebec_CAQ)
table(dat$vote_quebec, dat$vote_quebec_PQ)
table(dat$vote_quebec, dat$vote_quebec_PLQ)
table(dat$vote_quebec, dat$vote_quebec_QS)
table(dat$vote_quebec, dat$vote_quebec_vert)
table(dat$vote_quebec, dat$vote_quebec_autre)

table(dat$vote_canada, dat$vote_canada_liberal)
table(dat$vote_canada, dat$vote_canada_conservateur)
table(dat$vote_canada, dat$vote_canada_npd)
table(dat$vote_canada, dat$vote_canada_bloc)
table(dat$vote_canada, dat$vote_canada_vert)
table(dat$vote_canada, dat$vote_canada_autre)

table(dat$vote_france, dat$vote_france_enmarche)
table(dat$vote_france, dat$vote_france_republicains)
table(dat$vote_france, dat$vote_france_verts)
table(dat$vote_france, dat$vote_france_PS)
table(dat$vote_france, dat$vote_france_RN)
table(dat$vote_france, dat$vote_france_insoumise)

# Recode categorical variables
table(dat$emploi)
table(dat$revenu)
table(dat$economieCANADA_confiance)
table(dat$economieFRANCE_confiance)
table(dat$immigrationCANADA_confiance)
table(dat$immigrationFRANCE_confiance)

dat <- dat %>% 
  mutate(emploi = dplyr::recode(emploi, 
                                `1`= "Salarié à temps plein",
                                `2`="Salarié à temps partiel",
                                `3`="Travailleur autonome (avec ou sans employés)",
                                `4`="À la retraite",
                                `5`="Au chômage/à la recherche d’un travail",
                                `6`="Étudiant",
                                `7`="En charge d’une famille",
                                `8`="Handicapé",
                                `9`="Étudiant et salarié",
                                `10`="En charge d’une famille et salarié",
                                `11`="À la retraite et salarié",
                                `12`="Autre",
                                `13`="Je ne sais pas / Préfère ne pas répondre"),
         revenu = dplyr::recode(revenu, 
                                `1`="1.moins de $30,000",
                                `2`="2.$30,000 à $60,000",
                                `3`="3.$60,000 à $90,000",
                                `4`="4.$90,000 à 110,000",
                                `5`="5.Plus de $110,000",
                                `6`="6.Je ne sais pas / Préfère ne pas répondre)"),
         genre= recode(genre, 
                       `1` = "Homme", 
                       `2` =  "Femme", 
                       `3` = "Autre"),
         citoyennete = recode(citoyennete,
                              `1`="Canada",
                              `2`="États-Unis",
                              `3`="Chine-Hong Kong-Taiwan",
                              `4`="France",
                              `5`="Allemagne",
                              `6`="Inde",
                              `7`="Italie",
                              `8`="Pays-Bas",
                              `9`="Pologne",
                              `10`="Portugal",
                              `11`="Royaume-Uni",
                              `12`="Belgique",
                              `13`="Suisse",
                              `14`="Sénégal",
                              `15`="Côte d’Ivoire",
                              `16`="Brésil",
                              `17`="Mexique",
                              `18`="Autre"),
         ethnie = recode(ethnie,
                         `1`="Anglais",
                         `2`="Irlandais",
                         `3`="Britannique",
                         `4`="Français",
                         `5`="Italien",
                         `6`="Chinois",
                         `7`="Allemand",
                         `8`="Polonais",
                         `9`="Néérlandais",
                         `10`="Indien",
                         `11`="Écossais",
                         `12`="Ukrainien",
                         `13`="Autre"),
         education = recode(education,
                            `1`="1.Pas de diplôme / école primaire",
                            `2`="2.Secondaire / Collégiales / CEGEP / Lycée / DEP",
                            `3`="3.Universitaire premier cycle",
                            `4`="4.Universitaire deuxième cycle et plus"),
         religion = recode(religion,
                           `1`="1.Très important",
                           `2`="2.Assez important",
                           `3`="3.Pas très important",
                           `4`="4.Pas important du tout"),
         reseau_social = recode(reseau_social,
                                `1`="oui, beaucoup",
                                `2`="oui, quelques-uns",
                                `3`="non aucun"),
         residence = recode(residence,
                            `1`="Canada",
                            `2`="France",
                            `3`="États-Unis",
                            `4`="Belgique",
                            `5`="Suisse",
                            `6`="Autre"),
         province= recode(province,
                          `1`="CB",
                          `2`="AB",
                          `3`="SK",
                          `4`="MA",
                          `5`="ON",
                          `6`="QC",
                          `7`="NB",
                          `8`="NE",
                          `9`="IPE",
                          `10`="TNL",
                          `11`="YK",
                          `12`="NU",
                          `13`= "TNO"),
         classe_sociale= recode(classe_sociale,
                               `1` ="classe moyenne",
                               `2`="classe ouvrière",
                               `3`="classe supérieure"),
         province_naissance_parents= recode(province_naissance_parents,
                                            `1` ="oui",
                                            `2`="non",
                                            `3`="Je ne sais pas"),
         pays_naissance_parents = recode(pays_naissance_parents,
                                         `1` ="oui",
                                         `2`="non",
                                         `3`="Je ne sais pas"),
         climat_social= recode(climat_social,
                               `1`="amélioré",
                               `2`="détérioré",
                               `3`="resté stable"),
         covid_satisfaction= recode(covid_satisfaction,
                                    `1`="1.Très satisfait",
                                    `2`="2.Satisfait",
                                    `3`="3.Peu satisfait",
                                    `4`="4.Très insatisfait"),
         covid_gestion= recode(covid_gestion,
                               `1`="1.Très satisfait",
                               `2`="2.Satisfait",
                               `3`="3.Peu satisfait",
                               `4`="4.Très insatisfait"),
         covid_jeune = recode(covid_jeune,
                              `1`="Parti libéral",
                              `2`="NPD",
                              `3`="Parti vert",
                              `4`="Part conservateur",
                              `5`="Bloc Québécois",
                              `6`="Autre"),
         covid_politiques= recode(covid_politiques,
                                  `1`="Les politiques sont idéales",
                                  `2`="Les politiques sont adéquates, permettent à l'économie de rester stable",
                                  `3`="Les politiques sont adéquates, mais l'économie souffre",
                                  `4`="Les politiques sont mauvaises"),
         immigration_ouverture = recode(immigration_ouverture,
                                        `1`="1.Beaucoup plus d'ouverture",
                                        `2`="2.Un peu plus d'ouverture",
                                        `3`="3.Neutre",
                                        `4`="4.Moins d'ouverture",
                                        `5`="5.Beaucoup moins d'ouverture",
                                        `6`="6.Je ne sais pas"),
         immigration_syrie = recode(immigration_syrie,
                                    `1`="1.Fortement d’accord",
                                    `2`="2.Plutôt d’accord",
                                    `3`="3.Ni en accord, ni en désaccord",
                                    `4`="4.Assez en désaccord",
                                    `5`="5.Plutôt en désaccord",
                                    `6`="6.Fortement en désaccord"),
         climat_economie = recode(climat_economie,
                                  `1`="1.Fortement d’accord",
                                  `2`="2.Plutôt d’accord",
                                  `3`="3.Ni en accord, ni en désaccord",
                                  `4`="4.Assez en désaccord",
                                  `5`="5.Plutôt en désaccord",
                                  `6`="6.Fortement en désaccord"),
         transition_energetique_taxes= recode(transition_energetique_taxes,
                                              `1`="1.Fortement d’accord",
                                              `2`="2.Plutôt d’accord",
                                              `3`="3.Ni en accord, ni en désaccord",
                                              `4`="4.Assez en désaccord",
                                              `5`="5.Plutôt en désaccord",
                                              `6`="6.Fortement en désaccord"),
         climat_impact= recode(climat_impact,
                               `1`="1.Fortement d’accord",
                               `2`="2.Plutôt d’accord",
                               `3`="3.Ni en accord, ni en désaccord",
                               `4`="4.Assez en désaccord",
                               `5`="5.Plutôt en désaccord",
                               `6`="6.Fortement en désaccord"),
         confiance_police= recode(confiance_police,
                                  `1`="1.Fortement d’accord",
                                  `2`="2.Plutôt d’accord",
                                  `3`="3.Ni en accord, ni en désaccord",
                                  `4`="4.Assez en désaccord",
                                  `5`="5.Plutôt en désaccord",
                                  `6`="6.Fortement en désaccord"),
         securite_quartier = recode(securite_quartier,
                                    `1`="1.Fortement d’accord",
                                    `2`="2.Plutôt d’accord",
                                    `3`="3.Ni en accord, ni en désaccord",
                                    `4`="4.Assez en désaccord",
                                    `5`="5.Plutôt en désaccord",
                                    `6`="6.Fortement en désaccord"),
         securite_gouvernement= recode(securite_gouvernement,
                                       `1`="1.Fortement d’accord",
                                       `2`="2.Plutôt d’accord",
                                       `3`="3.Ni en accord, ni en désaccord",
                                       `4`="4.Assez en désaccord",
                                       `5`="5.Plutôt en désaccord",
                                       `6`="6.Fortement en désaccord"),
         securite_frontieres = recode(securite_frontieres,
                                      `1`="1.Fortement d’accord",
                                      `2`="2.Plutôt d’accord",
                                      `3`="3.Ni en accord, ni en désaccord",
                                      `4`="4.Assez en désaccord",
                                      `5`="5.Plutôt en désaccord",
                                      `6`="6.Fortement en désaccord"),
         immigration_quotas= recode(immigration_quotas,
                                    `1`="1.Fortement d’accord",
                                    `2`="2.Plutôt d’accord",
                                    `3`="3.Ni en accord, ni en désaccord",
                                    `4`="4.Assez en désaccord",
                                    `5`="5.Plutôt en désaccord",
                                    `6`="6.Fortement en désaccord"),
         minorites_partis = recode(minorites_partis,
                                   `1`="Parti libéral",
                                   `2`="Parti conservateur",
                                   `3`="NDP",
                                   `4`="Bloc Québécois",
                                   `5`="Parti vert",
                                   `6`="Autre",
                                   `7`="Je ne sais pas"),
         corruption= recode(corruption,
                            `1`="1.Très répandue",
                            `2`="2.Assez répandue",
                            `3`="3.Peu répandue",
                            `4`="4.Pas du tout répandue"),
         mondialisation = recode(mondialisation,
                                 `1`="1.Très bonne opinion",
                                 `2`="2.Plutôt bonne opinion",
                                 `3`="3.Ni bonne ni mauvaise opinion",
                                 `4`="4.Plutôt mauvaise opinion",
                                 `5`="5.Très mauvaise opinion"),
         economie_sociotropique = recode(economie_sociotropique,
                                         `1`="améliorée",
                                         `2`="détériorée",
                                         `3`="resté stable"),
         economie_egotropique = recode(economie_egotropique,
                                       `1`="améliorée",
                                       `2`="détériorée",
                                       `3`="resté stable"),
         economie_satisfaction = recode(economie_satisfaction,
                                        `1`="1.Très satisfaisant",
                                        `2`="2.Assez satisfaisant",
                                        `3`="3.Peu satisfaisant",
                                        `4`="4.Pas du tout satisfaisant",
                                        `5`="5.Sans opinion"),
         economie_preoccupation = recode(economie_preoccupation,
                                         `1`="1.Grandement",
                                         `2`="2.Moyennement",
                                         `3`="3.Peu",
                                         `4`="4.Pas du tout"),
         economie_criteres = recode(economie_criteres,
                                    `1`="Je vais faire un bilan des politiques mises en place pendant le mandat ",
                                    `2`="Je vais davantage m’intéresser aux politiques proposées",
                                    `3`="Je vais faire un croisement entre les politiques passées et les perspectives proposées"),
         economieCANADA_confiance = recode(economieCANADA_confiance, # revoir
                                           `1`="Parti libéral",
                                           `2`="Parti conservateur",
                                           `3`="NPD",
                                           `4`="Bloc Québécois",
                                           `5`="Parti vert",
                                           `6`="Non, aucun",
                                           `7`="Autre"),
         economieFRANCE_confiance = recode(economieFRANCE_confiance,# revoir
                                           `1`="Parti socialiste",
                                           `2`="République en marche",
                                           `3`="Républicains",
                                           `4`="France insoumise",
                                           `5`="Europe-écologie - Les verts",
                                           `6`="RN",
                                           `7`= "Aucun",
                                           `8` ="Autre"),
         immigrationCANADA_confiance = recode(immigrationCANADA_confiance,# revoir
                                              `1`="Parti libéral",
                                              `2`="Parti conservateur",
                                              `3`="NPD",
                                              `4`="Bloc Québécois",
                                              `5`="Parti vert",
                                              `6`="Non, aucun"),
         immigrationFRANCE_confiance = recode(immigrationFRANCE_confiance,# revoir
                                              `1`="Parti socialiste",
                                              `2`="République en marche",
                                              `3`="Républicains",
                                              `4`="France insoumise",
                                              `5`="Europe-écologie - Les verts",
                                              `6`="RN",
                                              `7`= "Aucun"),
         representation_minorites = recode(representation_minorites,
                                           `1`="1.Beaucoup plus importante",
                                           `2`="2.Plus importante",
                                           `3`="3.Ni plus ni moins importante",
                                           `4`="4.Moins importante",
                                           `5`="5.Beaucoup moins importante"),
         importance_ecologie = recode(importance_ecologie,
                                      `1`="1.Beaucoup",
                                      `2`="2.Un peu",
                                      `3`="3.Aucune",
                                      `4`="4.Ne sais pas"),
         inquietude_attentats = recode(inquietude_attentats,
                                       `1`="1.Particulièrement inquiet",
                                       `2`="2.Plutôt inquiet",
                                       `3`="3.Peu inquiet",
                                       `4`="4.Pas du tout inquiet",
                                       `5`="5.Sans opinion"),
         satisfaction_democracie = recode(satisfaction_democracie,
                                          `1`="1.Très satisfait",
                                          `2`="2.Assez satisfait",
                                          `3`="3.Peu satisfait",
                                          `4`="4.Pas du tout satisfait"),
         satisfaction_gouvernement = recode(satisfaction_gouvernement,
                                            `1`="1.Grandement satisfait",
                                            `2`="2.Moyennement satisfait",
                                            `3`="3.Peu satisfait",
                                            `4`="4.Pas du tout satisfait"),
         institutions_democratiques = recode(institutions_democratiques,
                                             `1`="J’y suis très attaché.e et je m’y intéresse beaucoup",
                                             `2`="Je ne m’y intéresse que pour certaines politiques publiques",
                                             `3`="Je ne m’y intéresse que très peu parce que je ne suis pas intéressé.e par a politique",
                                             `4`="Je ne m’y intéresse pas du tout parce que je n’y crois plus"),
         vote_demonstration = recode(vote_demonstration,
                                     `1`="Oui, totalement",
                                     `2`="Oui, mais de moins en moins",
                                     `3`="Non, pas envers l’élite politique mais la démocratie seulement",
                                     `4`="Non, cela n'a rien à voir"),
         confiance_ChefEtat = recode(confiance_ChefEtat,
                                     `1`="1.Pas confiance",
                                     `2`="2.Peu confiance",
                                     `3`="3.Confiance",
                                     `4`="4.Moyennement confiance",
                                     `5`="5.Beaucoup confiance"),
         altruisme_politiques= recode(altruisme_politiques,
                                      `1`="1.Pas du tout",
                                      `2`="2.Peu",
                                      `3`="3.Moyennement",
                                      `4`="4.Correctement",
                                      `5`="5.Beaucoup"),
         education_civique = recode(education_civique, 
                                    `1`= "1.Fortement d’accord",
                                     `2`="2.Plutôt d’accord",
                                     `3`="3.Ni en accord, ni en désaccord",
                                     `4`="4.Assez en désaccord",
                                     `5`="5.Plutôt en désaccord",
                                     `6`="6.Fortement en désaccord"),
         ecoles= recode(ecoles, 
                        `1`= "1.Fortement d’accord",
                         `2`="2.Plutôt d’accord",
                         `3`="3.Ni en accord, ni en désaccord",
                         `4`="4.Assez en désaccord",
                         `5`="5.Plutôt en désaccord",
                         `6`="6.Fortement en désaccord"),
         comprehension_elites = recode(comprehension_elites, 
                                       `1`= "1.Fortement d’accord",
                                        `2`="2.Plutôt d’accord",
                                        `3`="3.Ni en accord, ni en désaccord",
                                        `4`="4.Assez en désaccord",
                                        `5`="5.Plutôt en désaccord",
                                        `6`="6.Fortement en désaccord"),
         importance_vote= recode(importance_vote, 
                                 `1`= "1.Fortement d’accord",
                                  `2`="2.Plutôt d’accord",
                                  `3`="3.Ni en accord, ni en désaccord",
                                  `4`="4.Assez en désaccord",
                                  `5`="5.Plutôt en désaccord",
                                  `6`="6.Fortement en désaccord"),
         importance_representation = recode(importance_representation,
                                            `1`= "1.Fortement d’accord",
                                             `2`="2.Plutôt d’accord",
                                             `3`="3.Ni en accord, ni en désaccord",
                                             `4`="4.Assez en désaccord",
                                             `5`="5.Plutôt en désaccord",
                                             `6`="6.Fortement en désaccord"),
         disproportion_electorale = recode(disproportion_electorale,
                                           `1`= "1.Fortement d’accord",
                                            `2`="2.Plutôt d’accord",
                                            `3`="3.Ni en accord, ni en désaccord",
                                            `4`="4.Assez en désaccord",
                                            `5`="5.Plutôt en désaccord",
                                            `6`="6.Fortement en désaccord"),
         partis_votes = recode(partis_votes,
                               `1`= "1.Fortement d’accord",
                                `2`="2.Plutôt d’accord",
                                `3`="3.Ni en accord, ni en désaccord",
                                `4`="4.Assez en désaccord",
                                `5`="5.Plutôt en désaccord",
                                `6`="6.Fortement en désaccord"),
         votes_objectif = recode(votes_objectif,
                                 `1`= "1.Fortement d’accord",
                                  `2`="2.Plutôt d’accord",
                                  `3`="3.Ni en accord, ni en désaccord",
                                  `4`="4.Assez en désaccord",
                                  `5`="5.Plutôt en désaccord",
                                  `6`="6.Fortement en désaccord"),
         votes_delais = recode(votes_delais,
                               `1`= "1.Fortement d’accord",
                                `2`="2.Plutôt d’accord",
                                `3`="3.Ni en accord, ni en désaccord",
                                `4`="4.Assez en désaccord",
                                `5`="5.Plutôt en désaccord",
                                `6`="6.Fortement en désaccord"),
         reedition_compte = recode(reedition_compte,
                                   `1`= "1.Fortement d’accord",
                                    `2`="2.Plutôt d’accord",
                                    `3`="3.Ni en accord, ni en désaccord",
                                    `4`="4.Assez en désaccord",
                                    `5`="5.Plutôt en désaccord",
                                    `6`="6.Fortement en désaccord"),
         interet_politiqueUS = recode(interet_politiqueUS,
                                      `1`="1.Très intéressé",
                                      `2`="2.Intéressé",
                                      `3`="3.Indifférent",
                                      `4`="4.Peu intéressé",
                                      `5`="5.Désintéressé"),
         engagement_politique= recode(engagement_politique,
                                      `1`="Le vote",
                                      `2`="Manifestations et pétitions",
                                      `3`="Manifestations, pétitions et vote",
                                      `4`="Aucun",
                                      `5`="pas sûr"),
         proche_parti = recode(proche_parti,
                               `1`="Oui",
                               `2`="Non",
                               `3`="Ne sais pas"),
         representation_partis= recode(representation_partis,
                                       `1`="1.Tout à fait",
                                       `2`="2.De manière satisfaisante",
                                       `3`="3.Pas vraiment",
                                       `4`="4.Pas du tout",
                                       `5`="5.Ne s'applique pas"),
         mode_scrutin= recode(mode_scrutin,
                              `1`="1.Tout à fait satisfait",
                              `2`="2.Satisfait",
                              `3`="3.Neutre",
                              `4`="4.Peu satisfait",
                              `5`="5.Ne s'applique pas"),
         changement_scrutin= recode(changement_scrutin,
                                    `1`="1.Tout à fait en faveur",
                                    `2`="2.Plutôt en faveur",
                                    `3`="3.Sans opinion, neutre",
                                    `4`="4.Plutôt en défaveur",
                                    `5`="5.Tout à fait en défaveur",
                                    `6`="6.Ne s'applique pas"),
         source_information = recode(source_information,
                                     `1`="Télévision",
                                     `2`="Réseaux sociaux",
                                     `3`="Journaux",
                                     `4`="Articles internet"),
         reseausociaux_cause = recode(reseausociaux_cause,
                                      `1`="Oui, plusieurs fois",
                                      `2`="Oui, une fois",
                                      `3`="Non",
                                      `4`="Je n'utilise pas les réseaux sociaux"),
         medias_traditionnels = recode(medias_traditionnels,
                                       `1`="1.Beaucoup",
                                       `2`="2.Assez",
                                       `3`="3.Peu",
                                       `4`="4.Pas du tout"),
         consultation_sondage1 = recode(consultation_sondage1,
                                        `1`="Oui",
                                        `2`="Non",
                                        `3`="Ne sais pas"),
         consultation_sondageCANADA = recode(consultation_sondageCANADA,
                                             `1`="Parti libéral",
                                             `2`="Parti conservateur",
                                             `3`="NPD",
                                             `4`="Bloc Québécois",
                                             `5`="Parti vert"),
         consultation_sondageFRANCE = recode(consultation_sondageFRANCE,
                                             `1`="Parti socialiste",
                                             `2`="République en marche",
                                             `3`="Républicains",
                                             `4`="France insoumise",
                                             `5`="Europe-Écologie - Les verts",
                                             `6`="RN"),
         principale_source = recode(principale_source,
                                    `1`="Amis",
                                    `2`="Famille",
                                    `3`="Réseaux sociaux",
                                    `4`="journaux en ligne-papier"),
         engagement_reseauxsociaux= recode(engagement_reseauxsociaux,
                                           `1`="Oui",
                                           `2`="Un peu",
                                           `3`="Pas du tout"),
         abonnements_personnalites = recode(abonnements_personnalites,
                                            `1`="Oui, ceux qui partagent les opinions",
                                            `2`="Oui, de tous bords politiques",
                                            `3`="Non"),
         frequence_utilisation= recode(frequence_utilisation,
                                       `1`="1.Jamais",
                                       `2`="2.Rarement",
                                       `3`="3.Plusieurs fois par semaine",
                                       `4`="4.Moins d'une heure/jour",
                                       `5`="5.1-2 heure/jour",
                                       `6`="6.2-3 heures/jour",
                                       `7`="7.plus de 3 heures/jour"),
         contact_information= recode(contact_information,
                                     `1`="1.Jamais",
                                     `2`="2.Rarement",
                                     `3`="3.Souvent",
                                     `4`="4.Systématiquement"),
         plateforme= recode(plateforme,
                            `1`="Twitter",
                            `2`="Youtube",
                            `3`="Facebook",
                            `4`="Autre"),
         couverture_influence= recode(couverture_influence,
                                     `1`="1.Beaucoup",
                                     `2`="2.Assez",
                                     `3`="3.Peu",
                                     `4`="4.Pas du tout"),
         medias_neutralite= recode(medias_neutralite,
                                   `1`="1.Fortement d’accord",
                                   `2`="2.Plutôt d’accord",
                                   `3`="3.Ni en accord, ni en désaccord",
                                   `4`="4.Assez en désaccord",
                                   `5`="5.Plutôt en désaccord",
                                   `6`="6.Fortement en désaccord"),
         biais_medias= recode(biais_medias,
                              `1`="1.Fortement d’accord",
                              `2`="2.Plutôt d’accord",
                              `3`="3.Ni en accord, ni en désaccord",
                              `4`="4.Assez en désaccord",
                              `5`="5.Plutôt en désaccord",
                              `6`="6.Fortement en désaccord"),
         chaines_independance = recode(chaines_independance,
                                       `1`="1.Fortement d’accord",
                                       `2`="2.Plutôt d’accord",
                                       `3`="3.Ni en accord, ni en désaccord",
                                       `4`="4.Assez en désaccord",
                                       `5`="5.Plutôt en désaccord",
                                       `6`="6.Fortement en désaccord"),
         niveau_information= recode(niveau_information,
                                    `1`="1.Bien informé",
                                    `2`="2.Plutôt informé",
                                    `3`="3.Pas très informé",
                                    `4`="4.Pas du tout informé",
                                    `5`="5.Je ne sais pas"),
         confiance_contenuRS= recode(confiance_contenuRS,
                                     `1`="1.Pas confiance",
                                     `2`="2.Un peu confiance",
                                     `3`="3.Moyennement confiance",
                                     `4`="4.Beaucoup confiance",
                                     `5`="5.Totalement confiance"),
         confiance_TVRadio = recode(confiance_TVRadio,
                                    `1`="1.Pas confiance",
                                    `2`="2.Un peu confiance",
                                    `3`="3.Moyennement confiance",
                                    `4`="4.Beaucoup confiance",
                                    `5`="5.Totalement confiance"),
         confiance_presseecrite = recode(confiance_presseecrite,
                                         `1`="1.Pas confiance",
                                         `2`="2.Un peu confiance",
                                         `3`="3.Moyennement confiance",
                                         `4`="4.Beaucoup confiance",
                                         `5`="5.Totalement confiance"),
         site_parti= recode(site_parti,
                            `1`="Oui",
                            `2`="Incertain",
                            `3`="Non"),
         like_parti= recode(like_parti,
                            `1`="Oui",
                            `2`="Incertain",
                            `3`="Non"),
         vote_habitude= recode(vote_habitude,
                               `1`="Oui, je vote toujours",
                               `2`="Non, mais la plupart du temps",
                               `3`="Non, mais j'ai déjà voté",
                               `4`="Non, jamais"),
         anciens_presidents= recode(anciens_presidents,
                                    `1`="De Gaulle",
                                    `2`="Chirac",
                                    `3`="Sarkozy",
                                    `4`="Hollande",
                                    `5`="Macron"),
         aucune_preference = recode(aucune_preference,
                                    `1`="Choisir l'option la moins pire",
                                    `2`="Voter au hasard",
                                    `3`="Ne pas voter"),
         preference_parti = recode(preference_parti,
                                   `1`="Voter pour ce parti quand même",
                                   `2`="Voter pour le parti adverse en espérant passer un message",
                                   `3`="Ne pas voter"),
         satisfaction_modescrutin = recode(satisfaction_modescrutin,
                                           `1`="1.Tout à fait satisfait",
                                           `2`="2.Satisfait",
                                           `3`="3.Ni satisfait, ni insatisfait",
                                           `4`="4.Pas satisfait",
                                           `5`="5.Pas du tout satisfait"),
         vote_chancesfavoris= recode(vote_chancesfavoris,
                                     `1`="J'irais certainement voter",
                                     `2`="J'irais probablement voter",
                                     `3`="Je ne sais pas si je voterais",
                                     `4`="Je n'irais probablement pas voter",
                                     `5`="Je n'irais certainement pas voter"),
         motivation = recode(motivation,
                             `1`="L'idéologie",
                             `2`="Le candidat",
                             `3`="Ni l'un ni l'autre"),
         premier_choix= recode(premier_choix,
                               `1`="Oui",
                               `2`="Non",
                               `3`="Ne sais pas"),
         strategie_vote2= recode(strategie_vote2,
                                 `1`="Oui",
                                 `2`="Non",
                                 `3`="Ne sais pas"),
         autrechoix_frequence = recode(autrechoix_frequence,
                                       `1`="1.Toutes les élections",
                                       `2`="2.Une élection sur deux",
                                       `3`="3.Une élection sur trois",
                                       `4`="4.Une élection sur quatre ou plus",
                                       `5`="5.À aucune élection"),
         refus_voteCANADA= recode(refus_voteCANADA,
                                  `1`="Parti libéral",
                                  `2`="Parti conservateur",
                                  `3`="NPD",
                                  `4`="Bloc Québécois",
                                  `5`="Parti vert",
                                  `6`="Non, aucun"),
         refus_voteFRANCE= recode(refus_voteFRANCE,
                                  `1`="Parti socialiste",
                                  `2`="République en marche",
                                  `3`="Républicains",
                                  `4`="France insoumise",
                                  `5`="Europe-écologie - Les verts",
                                  `6`="RN",
                                  `7`= "Aucun"))

#### Reorder variables ####
dat <- dat %>% 
  dplyr::select(annee_naissance, age, emploi, revenu, genre, citoyennete, ethnie, minorite, education, religion, reseau_social, residence, naissance_pays_residence, cohabitation, droit_vote,
          province, naissance_province_residence, classe_sociale, classe_sociale_parents, langue, province_naissance_parents, pays_naissance_parents, climat_social, covid_satisfaction,
          covid_soin, covid_gestion, covid_inquietude, covid_jeune, covid_politiques, immigration_ouverture, immigration_syrie, climat_economie, transition_energetique_taxes,
          climat_impact, confiance_police, securite_quartier, securite_gouvernement, securite_immigration, securite_frontieres, immigration_quotas, minorites_partis, corruption,
          corruption_participation, corruption_evaluation_partis, mondialisation, economie_sociotropique, economie_egotropique, economie_satisfaction, economie_preoccupation, 
          economie_criteres, economieCANADA_confiance, economieFRANCE_confiance, immigrationCANADA_confiance, immigrationFRANCE_confiance, deficit, representation_minorites, enjeux_chomage,
          enjeux_environnement, enjeux_immigration, enjeux_economie, enjeux_education, enjeux_sante, importance_immigration, importance_ecologie, inquietude_attentats, ideologie,
          satisfaction_democracie, satisfaction_gouvernement, institutions_democratiques, vote_demonstration, confiance_ChefEtat, altruisme_politiques, education_civique, ecoles,
          comprehension_elites, importance_vote, importance_representation, disproportion_electorale, partis_votes, votes_objectif, votes_delais, reedition_compte, importance_chef,
          interet_politique, interet_politiqueUS, connaissances_politiqueUS, engagement_politique, proche_parti, importance_traits, trait_integrite, trait_leadership, trait_competence,
          trait_empathie, representation_partis, mode_scrutin, changement_scrutin, vote_nationaliste, integration_localite, parti_liberal, parti_conservateur, ndp, bloc_quebecois, parti_vert,
          source_information, reseausociaux_cause, medias_traditionnels, consultation_sondage1, consultation_sondageCANADA, consultation_sondageFRANCE, principale_source, engagement_reseauxsociaux,
          abonnements_personnalites, frequence_utilisation, inscription_reseauxsociaux, contact_information, plateforme, couverture_influence, medias_neutralite, influence_medias, biais_medias,
          chaines_independance, niveau_information, effet_debats, importance_debatsTV, confiance_contenuRS, confiance_TVRadio, confiance_presseecrite, site_parti, like_parti, sophistication_etatsunis,
          sophistication_freeland, sophistication_legault, sophistication_macron, sophistication_pence, sophistication_singh, participation, vote_quebec2018_CAQ, vote_quebec2018_PQ, vote_quebec2018_PLQ,
          vote_quebec2018_QS, vote_quebec2018_vert, vote_quebec2018_autre, vote_quebec2018_bulletinnul, vote_quebec2018_pasvote, vote_US, vote_habitude, vote_memeparti, vote_france_enmarche, 
          vote_france_republicains, vote_france_verts, vote_france_PS, vote_france_RN, vote_france_insoumise, vote_canada_liberal, vote_canada_conservateur, vote_canada_npd, vote_canada_bloc,
          vote_canada_vert, vote_canada_autre, vote_quebec_CAQ, vote_quebec_PQ, vote_quebec_PLQ, vote_quebec_QS, vote_quebec_vert, vote_quebec_autre, anciens_presidents, vote_strategique,
          aucune_preference, preference_parti, satisfaction_modescrutin, vote_chancesfavoris, importance_competence, motivation, premier_choix, strategie_vote2, autrechoix_frequence, 
          refus_voteCANADA, refus_voteFRANCE,
          ideologie_VD, vote_nationaliste_VD, participation_VD, vote_quebec2018_CAQ_VD, vote_quebec2018_PQ_VD, vote_quebec2018_PLQ_VD, 
          vote_quebec2018_QS_VD, vote_quebec2018_vert_VD, vote_quebec2018_autre_VD, vote_quebec2018_bulletinnul_VD, vote_quebec2018_pasvote_VD, 
          vote_US_VD, vote_france_enmarche_VD, vote_france_republicains_VD, vote_france_verts_VD, vote_france_PS_VD, vote_france_RN_VD, 
          vote_france_insoumise_VD, vote_canada_liberal_VD, vote_canada_conservateur_VD, vote_canada_npd_VD, vote_canada_bloc_VD, vote_canada_vert_VD, 
          vote_canada_autre_VD, vote_quebec_CAQ_VD, vote_quebec_PQ_VD, vote_quebec_PLQ_VD, vote_quebec_QS_VD, vote_quebec_vert_VD, vote_quebec_autre_VD, 
          anciens_presidents_VD, vote_strategique_VD, changement_scrutin_VD) %>% 
  arrange(annee_naissance, age, emploi, revenu, genre, citoyennete, ethnie, minorite, education, religion, reseau_social, residence, naissance_pays_residence, cohabitation, droit_vote,
          province, naissance_province_residence, classe_sociale, classe_sociale_parents, langue, province_naissance_parents, pays_naissance_parents, climat_social, covid_satisfaction,
          covid_soin, covid_gestion, covid_inquietude, covid_jeune, covid_politiques, immigration_ouverture, immigration_syrie, climat_economie, transition_energetique_taxes,
          climat_impact, confiance_police, securite_quartier, securite_gouvernement, securite_immigration, securite_frontieres, immigration_quotas, minorites_partis, corruption,
          corruption_participation, corruption_evaluation_partis, mondialisation, economie_sociotropique, economie_egotropique, economie_satisfaction, economie_preoccupation, 
          economie_criteres, economieCANADA_confiance, economieFRANCE_confiance, immigrationCANADA_confiance, immigrationFRANCE_confiance, deficit, representation_minorites, enjeux_chomage,
          enjeux_environnement, enjeux_immigration, enjeux_economie, enjeux_education, enjeux_sante, importance_immigration, importance_ecologie, inquietude_attentats, ideologie,
          satisfaction_democracie, satisfaction_gouvernement, institutions_democratiques, vote_demonstration, confiance_ChefEtat, altruisme_politiques, education_civique, ecoles,
          comprehension_elites, importance_vote, importance_representation, disproportion_electorale, partis_votes, votes_objectif, votes_delais, reedition_compte, importance_chef,
          interet_politique, interet_politiqueUS, connaissances_politiqueUS, engagement_politique, proche_parti, importance_traits, trait_integrite, trait_leadership, trait_competence,
          trait_empathie, representation_partis, mode_scrutin, changement_scrutin, vote_nationaliste, integration_localite, parti_liberal, parti_conservateur, ndp, bloc_quebecois, parti_vert,
          source_information, reseausociaux_cause, medias_traditionnels, consultation_sondage1, consultation_sondageCANADA, consultation_sondageFRANCE, principale_source, engagement_reseauxsociaux,
          abonnements_personnalites, frequence_utilisation, inscription_reseauxsociaux, contact_information, plateforme, couverture_influence, medias_neutralite, influence_medias, biais_medias,
          chaines_independance, niveau_information, effet_debats, importance_debatsTV, confiance_contenuRS, confiance_TVRadio, confiance_presseecrite, site_parti, like_parti, sophistication_etatsunis,
          sophistication_freeland, sophistication_legault, sophistication_macron, sophistication_pence, sophistication_singh, participation, vote_quebec2018_CAQ, vote_quebec2018_PQ, vote_quebec2018_PLQ,
          vote_quebec2018_QS, vote_quebec2018_vert, vote_quebec2018_autre, vote_quebec2018_bulletinnul, vote_quebec2018_pasvote, vote_US, vote_habitude, vote_memeparti, vote_france_enmarche, 
          vote_france_republicains, vote_france_verts, vote_france_PS, vote_france_RN, vote_france_insoumise, vote_canada_liberal, vote_canada_conservateur, vote_canada_npd, vote_canada_bloc,
          vote_canada_vert, vote_canada_autre, vote_quebec_CAQ, vote_quebec_PQ, vote_quebec_PLQ, vote_quebec_QS, vote_quebec_vert, vote_quebec_autre, anciens_presidents, vote_strategique,
          aucune_preference, preference_parti, satisfaction_modescrutin, vote_chancesfavoris, importance_competence, motivation, premier_choix, strategie_vote2, autrechoix_frequence, 
          refus_voteCANADA, refus_voteFRANCE,
          ideologie_VD, vote_nationaliste_VD, participation_VD, vote_quebec2018_CAQ_VD, vote_quebec2018_PQ_VD, vote_quebec2018_PLQ_VD, 
          vote_quebec2018_QS_VD, vote_quebec2018_vert_VD, vote_quebec2018_autre_VD, vote_quebec2018_bulletinnul_VD, vote_quebec2018_pasvote_VD, 
          vote_US_VD, vote_france_enmarche_VD, vote_france_republicains_VD, vote_france_verts_VD, vote_france_PS_VD, vote_france_RN_VD, 
          vote_france_insoumise_VD, vote_canada_liberal_VD, vote_canada_conservateur_VD, vote_canada_npd_VD, vote_canada_bloc_VD, vote_canada_vert_VD, 
          vote_canada_autre_VD, vote_quebec_CAQ_VD, vote_quebec_PQ_VD, vote_quebec_PLQ_VD, vote_quebec_QS_VD, vote_quebec_vert_VD, vote_quebec_autre_VD, 
          anciens_presidents_VD, vote_strategique_VD, changement_scrutin_VD)

custom_glimpse <- function(df) {
  data.frame(
    col_name = colnames(df),
    col_index = 1:ncol(df),
    col_class = sapply(df, class),
    row.names = NULL
  )
}
variable_nb <- custom_glimpse(dat)

#### Variables class ####
class(dat$education)
table(dat$education)
class(dat$participation_VD)

#### Group variable types #####

# categorical variables - 102 variables
categorical_variables <- c("Emploi" = 3, 
                           "Revenu" = 4,
                           "Genre" = 5,
                           "Citoyenneté" = 6,
                           "Ethnie" = 7,
                           "Éducation" = 9,
                           "Religion" = 10,
                           "Réseau social" = 11,
                           "Résidence" = 12,
                           "Province" = 16, 
                           "Classe sociale" = 18,
                           "Résidence parents - province" = 21,
                           "Residence parents - pays" = 22,
                           "Climat social" = 23,
                           "Covid - satisfaction" = 24,
                           "Covid - gestion" = 26,
                           "Covid - jeunes" = 28,
                           "Covid - politiques" = 29,
                           "Immigration - ouverture" = 30, 
                           "Immigration - Syrie" = 31,
                           "Climat - économie" = 32,
                           "Transition énergétique - taxes" = 33,
                           "Climat - impacts" = 34,
                           "Confiance - police" = 35,
                           "Sécurité - quartier" = 36,
                           "Sécurité - gouvernement" = 37,
                           #"Sécurité - immigration" = 38,
                           "Sécurité - frontières" = 39, 
                           "Immigration - quotas" = 40,
                           "Mninorités - partis" = 41,
                           "Corruption" = 42,
                           "Mondialisation" = 45,
                           "Économie - évaluation sociotropique" = 46,
                           "Économie - évaluation égotropique" = 47,
                           "Économie - statisfaction" = 48,
                           "Économie - préoccupation" = 49,
                           "Économie - critères" = 50, 
                           "Économie - confiance (Canada)" = 51,
                           "Économie - confiance (France)" = 52,
                           "Immigration - confiance (Canada)" = 53,
                           "Immigration - confiance (France)" = 54,
                           "Représentation des minorités" = 56,
                           "Importance - écologie" = 64,
                           "Inquiétude - attentats" = 65,
                           "Satisfaction envers la démocratie" = 67,
                           "Satisfaction Gouvernement" = 68, 
                           "Institutions démocratiques" = 69,
                           "Vote - démonstration" = 70,
                           "Confiance - Chef de l'État" = 71,
                           "Altruisme - politiques" = 72,
                           "Education civique" = 73,
                           "Écoles" = 74,
                           "Compréhension - élites" = 75,
                           "Importance vote" = 76,
                           "Importance - représentation" = 77, 
                           "Disproportion électorale" = 78,
                           "Partis - vote" = 79,
                           "Votes - objectif" = 80,
                           "Vote - délais" = 81,
                           "Réédition de comptes" = 82,
                           "Intérêt - politique US" = 85,
                           "Engagement politique" = 87,
                           "Proche parti" = 88,
                           "Représentation = partis" = 94, 
                           "Mode de scrutin" = 95,
                           "Changement scrutin" = 96,
                           "Sources d'information" = 104,
                           "Réseaux sociaux - cause" = 105,
                           "Médias traditionnels" = 106,
                           "Consultation sondage - 1" = 107,
                           "Consultation sondage 2 - Canada" = 108,
                           "Consultation sondage 2 - France" = 109,
                           "Principale source" = 110, 
                           "Engagement - réseaux sociaux" = 111,
                           "Abonnements - personnalités" = 112,
                           "Fréquence utilisation" = 113,
                           "Contact - information" = 115,
                           "Plateforme" = 116,
                           "Couverture - influence" = 117,
                           "Médias - neutralité" = 118,
                           #"Influence des médias sur l'élection" = 119,
                           "Biais médias" = 120, 
                           "Chaînes - indépendance" = 121,
                           "Niveau d'information" = 122,
                           "Confiance contenu RS" = 125,
                           "Confiance - TV et radio" = 126,
                           "Confiance - presse écrite" = 127,
                           "Site - parti" = 128,
                           "Like - parti" = 129,
                           "Vote habitude" = 146,
                           "Vote - anciens présidents" = 166, 
                           "Aucune préférence" = 168,
                           "Préférence - parti" = 169,
                           "Satisfaction mode de scrutin" = 170,
                           "Vote - chance favoris" = 171,
                           "Motivation" = 173,
                           "Vote - premier choix" = 174,
                           "Stratégie - vote 2" = 175,
                           "Autre choix - fréquence" = 176, 
                           "Refus de voter pour un parti - Canada" = 177,
                           "Refus de voter pour un parti - France" = 178)

# dichotomous varibales - 44 variables
dichotomous_variables <- c("Minorité" = 8, 
                           "Naissance pays résidence" = 13,
                           "Cohabitation" = 14,
                           "Droit de vote" = 15,
                           "Né.e dans votre province de résidence" = 17,
                           "Classe sociale - parents" = 19,
                           "Langue" = 20,
                           "Covid - accès aux soins" = 25,
                           "Déficit" = 55,
                           "Sophistication - États-Unis" = 130, 
                           "Sophistication - Freeland" = 131,
                           "Sophistication - Legault" = 132,
                           "Sophistication - Macron" = 133,
                           "Sophistication - Pence" = 134,
                           "Sophistication - Singh" = 135,
                           "Participation" = 136,
                           "Québec 2018 - CAQ" = 137,
                           "Québec 2018 - PQ" = 138,
                           "Québec 2018 - PLQ" = 139, 
                           "Québec 2018 - QS" = 140,
                           "Québec 2018 - PVQ" = 141,
                           "Québec 2018 - Autre" = 142,
                           "Québec 2018 - Bulletin nul" = 143,
                           "Québec 2018 - Pas voté" = 144,
                           "Vote - US" = 145,
                           "Vote - même parti" = 147,
                           "Intention de vote France - République en marche" = 148,
                           "Intention de vote France - Républicains" = 149, 
                           "Intention de vote France - Verts" = 150,
                           "Intention de vote France - PS" = 151,
                           "Intention de vote France - RN" = 152,
                           "Intention de vote France - France insoumise" = 153,
                           "Intention de vote Canada - Libéral" = 154,
                           "Intention de vote Canada - Conservateur" = 155,
                           "Intention de vote Canada - NPD" = 156,
                           "Intention de vote Canada - Bloc" = 157,
                           "Intention de vote Canada - Vert" = 158,
                           "Intention de vote Canada - Autre" = 159,
                           "Intention de vote Québec - CAQ" = 160,
                           "Intention de vote Québec - PQ" = 161,
                           "Intention de vote Québec - PLQ" = 162,
                           "Intention de vote Québec - QS" = 163,
                           "Intention de vote Québec - PVQ" = 164,
                           "Intention de vote Québec - Autre" = 165)

# continuous variables - 31 variables
continuous_variables <- c("Année de naissance" = 1, 
                          "Âge" = 2,
                          "Covid - inquiétude" = 27, 
                          "Corruption - participation" = 43,
                          "Corruption - évaluation des partis" = 44, 
                          "Enjeux - chômage" = 57,
                          "Enjeux - environnement" = 58, 
                          "Enjeux - immigration" = 59,
                          "Enjeux - économie" = 60, 
                          "Enjeux - éducation" = 61,
                          "Enjeux - santé" = 62,
                          "Importance - immigration" = 63,
                          "Idéologie" = 66,
                          "Importance - chef" = 83, 
                          "Intérêt politique" = 84,
                          "Connaissances - politique US" = 86, 
                          "Importance traits" = 89,
                          "Traits - importance - intégrité" = 90, 
                          "Traits - importance - leadership" = 91,
                          "Traits - importance - compétence" = 92, 
                          "Traits - importance - empathie" = 93,
                          "Vote parti nationaliste" = 97, 
                          "Intégration localité" = 98,
                          "Thermomètre partis - Libéral" = 99, 
                          "Thermomètre partis - Conservateur" = 100,
                          "Thermomètre partis - NPD" = 101, 
                          "Thermomètre partis - Bloc" = 102,
                          "Thermomètre partis - Parti vert" = 103, 
                          "Inscription réseaux sociaux" = 114,
                          "Effet - débats" = 123, 
                          "Importance débats TV" = 124,
                          "Vote stratégique" = 167,
                          "Importance compétence" = 172)

# dependent variables
dependent_variables <- c("Idéologie" = 179,
                         "Vote - parti nationaliste" = 180,
                         "Participation" = 181,
                         "Québec 2018 - CAQ" = 182,
                         "Québec 2018 - PQ" = 183,
                         "Québec 2018 - PLQ" = 184,
                         "Québec 2018 - QS" = 185,
                         "Québec 2018 - Vert" = 186,
                         "Québec 2018 - Autre" = 187,
                         "Québec 2018 - Bulletin nul" = 188,
                         "Québec 2018 - Pas voté" = 189,
                         "Vote - US" = 190,
                         "Intention de vote France - République en marche" = 191,
                         "Intention de vote France - Républicains" = 192,
                         "Intention de vote France - Verts" = 193,
                         "Intention de vote France - PS" = 194,
                         "Intention de vote France - RN" = 195,
                         "Intention de vote France - Insoumise" = 196,
                         "Intention de vote Canada - Liberal" = 197,
                         "Intention de vote Canada - Conservateur" = 198,
                         "Intention de vote Canada - NPD" = 199,
                         "Intention de vote Canada - Bloc" = 200,
                         "Intention de vote Canada - Vert" = 201,
                         "Intention de vote Canada - Autre" = 202,
                         "Intention de vote Québec - CAQ" = 203,
                         "Intention de vote Québec - PQ" = 204,
                         "Intention de vote Québec - PLQ" = 205,
                         "Intention de vote Québec - QS" = 206,
                         "Intention de vote Québec - Vert" = 207,
                         "Intention de vote Québec - Autre" = 208,
                         "Vote - anciens présidents" = 209,
                         "Vote stratégique" = 210,
                         "Changement de scrutin" = 211)

# categorical and dichotomous variables (for cross tabs)
cat_dicho_variables <- c(categorical_variables,  dichotomous_variables)

# dependent variables only (dichotomous or continuous)
#dependent_variables <- c(continuous_variables, dichotomous_variables)

# all variables
variables <- c(categorical_variables, dichotomous_variables, continuous_variables)

# convert categorical and dichotomous variables to factor 
#dat[cat_dicho_variables] <- sapply(dat[cat_dicho_variables], as.factor)
summary(dat$education)
summary(dat$genre)
table(dat$genre)
summary(dat$annee_naissance)
summary(dat$enjeux_chomage)
summary(dat$vote_strategique)
summary(dat$participation_VD)
class(dat$participation_VD)

# paste column names to values of categorical variables
# test <- dat[categorical_variables]
# test[] <- paste(colnames(test), as.matrix(test), sep = "")
# table(test$ethnie)
# class(test)

#### Save ####

write.csv(dat, "POL-3015/data/sondage_recoded.csv")


###################


test <- read.csv("appli-cours/data/sondage_recoded.csv") %>% dplyr::select(-X)
y <- test[, as.numeric(test$age)]
y <- test %>% dplyr::select(trait_competence)
x <- test %>% dplyr::select(age)
df <- data.frame(y,x)

model <- lm(trait_competence ~ age, data = test) %>% 
  broom::tidy() %>% 
  mutate(term = ifelse(term == "(Intercept)", "constante", 
                       ifelse(term == "x", names(d[as.numeric(input$iv)]), term))) %>% # ifelse(str_detect(term, "x"), str_remove(term, "x"), 
  rename(` ` = term,
         Coefficient = estimate,
         `Erreur-type` = std.error,
         `Statistique t` = statistic,
         `Valeur p` = p.value)