---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Codebook 

# {.tabset .tabset-fade .tabset-pills}

## Socio-démographiques

<h3>Année de naissance</h3>

Quelle est votre année de naissance ?

<h3>Age</h3>

Variable année de naissance recodée.

<h3>Emploi</h3>

Quel est votre statut d’emploi actuel?

1.  Salarié à temps plein

2.  Salarié à temps partiel

3.  Travailleur autonome (avec ou sans employés)

4.  À la retraite

5.  Au chômage/à la recherche d’un travail

6.  Étudiant

7.  En charge d’une famille

8.  Handicapé

9.  Étudiant et salarié

10. En charge d’une famille et salarié

11. À la retraite et salarié

12. Autre

13. Je ne sais pas / Préfère ne pas répondre

<h3>Revenu</h3>

Le revenu de votre ménage tombe-t-il dans l’une des catégories suivantes
:

1.  moins de \$30,000

2.  \$30,000 à \$60,000

3.  \$60,000 à \$90,000

4.  \$90,000 à 110,000

5.  Plus de \$110,000

6.  Je ne sais pas / Préfère ne pas répondre

<h3>Genre</h3>

Quel est votre genre ?

1.  Homme

2.  Femme

3.  Autre

<h3>Citoyenneté</h3>

Dans quel pays êtes-vous né(e) ?

1.  Canada

2.  États-Unis

3.  Chine-Hong Kong-Taiwan

4.  France

5.  Allemagne

6.  Inde

7.  Italie

8.  Pays-Bas

9.  Pologne

10. Portugal

11. Royaume-Uni

12. Belgique

13. Suisse

14. Sénégal

15. Côte d’Ivoire

16. Brésil

17. Mexique

18. Autre

<h3>Ethnie</h3>

(si canadien) A quel groupe ethnique ou culturel appartenez-vous, ou vos
ancêtres appartenaient-ils, au moment d’arriver au Canada ?

1.  Anglais

2.  Irlandais

3.  Britannique

4.  Français

5.  Italien

6.  Chinois

7.  Allemand

8.  Polonais

9.  Néerlandais

10. Indien

11. Écossais

12. Ukrainien

13. Autre

<h3>Minorité</h3>

Le gouvernement canadien définit les minorités visibles comme étant des
“personnes, autres que les Autochtones, qui ne sont pas de race blanche
ou qui n’ont pas la peau blanche”. Faites-vous partie d’une minorité
visible ?

1.  Oui

2.  Non

<h3>Education</h3>

Quel est votre niveau d’éducation ?

1.  Pas de diplôme / école primaire

2.  Secondaire / Collégiales / CEGEP / Lycée / DEP

3.  universitaire premier cycle

4.  universitaire deuxième cycle et plus

<h3>Religion, importance</h3>

Indépendamment du fait que vous apparteniez à une religion ou non,
quelle est l’importance de vos croyances religieuses ou spirituelles sur
la façon dont vous vivez votre vie ?

1.  Très important

2.  assez important

3.  pas très important

4.  pas important du tout

<h3>Reseau social</h3>

Avez-vous des amis ou des connaissances issus de l’immigration ?

1.  oui beaucoup

2.  oui quelques-uns

3.  non aucun

<h3>Résidence</h3>

Dans quel pays résidez-vous actuellement ?

1.  Canada

2.  France

3.  États-Unis

4.  Belgique

5.  Suisse

6.  Autre

<h3>Naissance résidence</h3>

Êtes-vous né(e) dans ce pays ?

1.  Oui

2.  Non

<h3>Cohabitation</h3>

Habitez-vous encore chez vos parents ?

1.  Oui

2.  Non

<h3>Droit de vote</h3>

Avez-vous le droit de vote dans votre pays de résidence ?

1.  Oui

2.  Non

<h3>Province</h3>

Dans quelle province ou territoire résidez-vous actuellement ?

1.  Colombie-Britannique

2.  Alberta

3.  Saskatchewan

4.  Manitoba

5.  Ontario

6.  Québec

7.  Nouveau-Brunswick

8.  Nouvelle-Écosse

9.  Île-du-Prince-Édouard

10. Terre-Neuve-et-Labrador

11. Yukon

12. Nunavut

13. Territoires du Nord-Ouest

<h3>Né(e) dans votre province de résidence</h3>

1.  Oui

2.  Non

<h3>Classe sociale</h3>

Si on vous demandait d’utiliser l’un de ces quatre termes pour désigner
votre classe sociale, à laquelle diriez-vous que vous appartenez ?

1.  classe moyenne

2.  classe ouvrière

3.  classe supérieure

<h3>Classe sociale - parents</h3>

Pensez-vous appartenir à la même classe sociale que vos parents ?

1.  Oui

2.  Non

<h3>Langue</h3>

La langue la plus souvent parlée à la maison est-elle une des langues
officielles de votre pays ? 

1.  Oui

2.  Non

<h3>Résidence parents - province</h3>

Vos parents sont ils nés dans la province/region ou vous résidez
actuellement

1.  Oui

2.  Non

3.  Je ne sais pas

<h3>Résidence parents - pays </h3>

Vos parents sont ils nés dans le pays ou vous résidez actuellement

1.  Oui

2.  Non

3.  Je ne sais pas

## Enjeux

<h3>Climat social</h3>

Que pensez-vous d’une manière générale du climat social actuel dans
votre pays ? S’est-il amélioré, détérioré ou est-il resté stable ?

1.  Amélioré

2.  Détérioré

3.  Resté stable

<h3>Covid - Satisfaction</h3>

Dans quelle mesure êtes-vous satisfait de la gestion du gouvernement en
place à ce qui a trait à la gestion de la crise sanitaire de la covid-19
?

1.  Très satisfait

2.  Satisfait

3.  Peu satisfait

4.  Très insatisfait

<h3>Covid - accès aux soins</h3>

Trouvez-vous que la même qualité de soins est accessible en régions que
dans les grands centres métropolitains ?

1.  Oui

2.  Non

<h3>Covid - Gestion</h3> 

Êtes-vous satisfait avec les efforts du gouvernement pour gérer les
conséquences négatives de la COVID-19 ?

1.  Très satisfait

2.  Satisfait

3.  Peu satisfait

4.  Très insatisfait

<h3>Covid - inquiétude</h3>

Indiquez sur une échelle de 0 à 10 votre niveau d’inquiétude pour votre
avenir suite à la crise engendrée par la COVID-19 (0 = Pas du tout
inquiet, 10 = Très inquiet)

<h3>Covid - jeunes</h3>

Quel parti vous semble le plus concerné par l’avenir des jeunes
générations face aux répercussions de la COVID-19 ?

1.  Parti libéral

2.  NPD

3.  Parti vert

4.  Parti conservateur

5.  Bloc Québécois

6.  Autre

<h3>Covid - politiques </h3>

Parmi les choix de réponses suivants, choisissez la suggestion qui
répond le mieux, selon vous, à la question suivante : Comment
décririez-vous les politiques économiques appliquées par votre
gouvernement en réponse à la crise économique liée à la pandémie ?

1.  Les politiques économiques appliquées sont idéales dans les
    circonstances actuelles, et permettent à l’économie du pays de
    prospérer malgré la présente crise économique liée à la pandémie.

2.  Les politiques économiques appliquées sont adéquates dans les
    circonstances actuelles, et permettent à l’économie du pays de
    rester stable malgré la présente crise économique liée à la
    pandémie.

3.  Les politiques économiques appliquées sont adéquates dans les
    circonstances actuelles, mais l’économie du pays souffre
    inévitablement de la présente crise économique liée à la pandémie.

4.  Les politiques économiques appliquées sont mauvaises dans les
    circonstances actuelles et l’économie du pays en souffre, en plus de
    souffrir de la présente crise économique liée à la pandémie.

<h3>Immigration - ouverture</h3>

En matière d’ouverture des frontières à l’immigration que souhaitez-vous?

1.  Beaucoup plus d’ouverture

2.  Un peu plus d’ouverture

3.  Neutre

4.  Moins d’ouverture

5.  Beaucoup moins d’ouverture

6.  Je ne sais pas

<h3>Immigration - Syrie</h3>

Les pays devraient refuser l’immigration de réfugiés en provenance de la
Syrie

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Climat - économie</h3>

Il est important que les gouvernements fassent de la lutte contre les
changements climatiques une priorité, même si cela veut dire que
l’économie va en souffrir

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Transition énergétique - taxes</h3>

Le gouvernement en place devrait hausser les taxes et hausser la retenue
d’impôt dans le but de financer une transition énergétique verte

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Climat - impacts</h3>

Les changements climatiques sont une réalité et nous devons agir dans
l’urgence pour limiter leurs impacts

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Confiance police</h3>

Vous avez confiance dans la police

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Sécurité - quartier</h3>

Vous vous sentez en sécurité dans votre quartier

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Sécurité - gouvernement</h3>

Il est important d’avoir un gouvernement fort assurant la sécurité

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Sécurité - frontières</h3>

Le gouvernement doit augmenter la sécurité des frontières nationales

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Immigration - quotas</h3>

Il est nécessaire que le gouvernement réduise le nombre d’immigrants
accueilli annuellement

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Minorités - partis</h3>

Au Canada, lequel des partis suivants associez-vous le plus avec les
minorités visibles et les immigrants ?

1.  Parti Libéral

2.  Parti conservateur

3.  NDP

4.  Bloc Québécois

5.  Le Parti vert

6.  Autre

7.  Je ne sais pas

<h3>Corruption</h3>

Estimez-vous que la corruption (comme par exemple recevoir des
pots-de-vin) est répandue parmi les responsables politiques de votre
pays?

1.  Très répandue

2.  Assez répandue

3.  Peu répandue

4.  Pas du tout répandue

<h3>Corruption - participation</h3>

Sur une échelle de 0 à 10, notez la force qu’un scandale de corruption
peut avoir comme influence sur votre participation électorale ?

<h3>Corruption - évaluation des partis</h3>

Quelle est votre évaluation d’un parti politique lorsqu’il est accusé de
corruption, 0 étant aucun changement d’opinion et 10 étant opinion très
impactée.

<h3>Mondialisation</h3>

D’une manière générale, diriez-vous que vous avez une bonne ou une
mauvaise opinion de la mondialisation ?

1.  Très bonne opinion

2.  Plutôt bonne opinion

3.  Ni bonne ni mauvaise opinion

4.  Plutôt mauvaise opinion

5.  Très mauvaise opinion

<h3>Économie - évaluation sociotropique</h3>

Depuis un an, l’économie de votre pays s’est-elle améliorée, détériorée,
ou restée à peu près la même ?

1.  Améliorée

2.  Détériorée

3.  Restée à peu près la même

<h3>Économie - évaluation égotropique</h3>

Depuis un an, votre situation financière s’est-elle améliorée,
détériorée, ou restée à peu près la même ?

1.  Améliorée

2.  Détériorée

3.  Restée à peu près la même

<h3>Économie - satisfaction</h3>

Quel est votre degré général de satisfaction à l’égard de votre
situation économique actuelle ?

1.  Très satisfaisant

2.  Assez satisfaisant

3.  Peu satisfaisant

4.  Pas du tout satisfaisant

5.  Sans opinion

<h3>Économie - Préoccupation</h3>

À quel point la situation économique dans votre pays vous préoccupe
t-elle ?

1.  Grandement

2.  Moyennement

3.  Peu

4.  Pas du tout

<h3>Économie - critères</h3>

Parmi les choix de réponses suivants, choisissez laquelle répond le
mieux, selon vous, à la question suivante : Comment évaluerez-vous
l’économie de votre pays aux prochaines élections ?

1.  Je vais faire un bilan des politiques économiques mises en place
    pendant le mandat du chef d’État sortant, évaluer s’il est bon ou
    mauvais, et soutenir un candidat notamment en fonction de ces
    données.

2.  Je vais davantage m’intéresser aux politiques économiques proposées
    par les différents partis durant la campagne électorale, et soutenir
    un candidat notamment en fonction de ces données.

3.  Je vais faire un croisement entre les politiques économique du
    gouvernement et les perspectives économiques futures proposées par
    les différents partis politiques, et soutenir un candidat notamment
    en fonction de ces données.

<h3>Économie [Canada / France]- confiance</h3>

A quel parti politique faites-vous confiance en terme de gestion de
l’économie ? [partis cf. intentions de vote dans le pays]\

Note: deux variables, economieCANADA\_confiance et
economieFRANCE\_confiance

<h3>Immigration [Canada / France] - confiance</h3>

Quel parti pensez-vous être capable de mieux gérer la question
migratoire ? [choix de réponse cf. choix de vote dans le pays]\

Note: deux variables, immigrationCANADA\_confiance et
immigrationFRANCE\_confiance

<h3>Déficit</h3>

Que devrait faire le gouvernement de votre pays pour aider l’économie :
équilibrer le budget ou produire un déficit ?

1.  Équilibrer le budget

2.  Produire un déficit

<h3>Représentation des minorités</h3>

Selon le Centre de recherche-action sur les relations raciales (CRARR),
on compterait 8% de députés (10 sur 125) qui sont des minorités visibles
à l’Assemblée Nationale du Québec. Selon vous, la représentation
politique des minorités visibles devrait être:

1.  Beaucoup plus importante

2.  Plus importante

3.  Ni plus ni moins importante

4.  Moins importante

5.  Beaucoup moins importante

<h3>Enjeux - importants [une variable par enjeu]</h3>

Classez ces enjeux par ordre de l’importance selon vous : chômage,
environnement, immigration, économie, éducation, santé publique.\

1.  enjeux\_chomage : rang chomage

2.  enjeux\_environnement : rang environnement

3.  enjeux\_immigration : rang immigration

4.  enjeux\_economie : rang économie

5.  enjeux\_education : rang éducation

6.  enjeux\_sante : rang santé publique

<h3>Importance - Immigration</h3>

Sur une échelle de 0 à 10, à quel degré évaluez-vous l’importance de
l’immigration comme sujet de préoccupation ? 0 indiquant aucune
inquiétude et 10 comme priorité principale

<h3>Importance - écologie</h3>

Quelle attention accordez-vous à l’écologie ?

1.  Beaucoup

2.  Un peu

3.  Aucune

4.  Ne sais pas

<h3>Inquiétude - attentats</h3>

[Si le répondant est Français] Suite aux attentats qu’a connu la France
depuis 2015, êtes-vous:

1.  particulièrement inquiet

2.  plutôt inquiet

3.  peu inquiet

4.  pas du tout inquiet

5.  sans opinion


## Attitudes politiques

<h3>Idéologie</h3>

En politique il est souvent fait référence à la “gauche” et à la
“droite”. Où vous placeriez-vous sur l’échelle gauche- droite ? (0 =
Extrême gauche , 5 = Centre,  10 = Extrême droite).

<h3>Satisfaction avec la démocratie</h3>

Dans l’ensemble, êtes-vous très satisfait(e), assez satisfait(e), peu
satisfait(e) ou pas du tout satisfait e du fonctionnement de la
démocratie dans votre pays ?

1.  Très satisfait(e)

2.  Assez satisfait(e)

3.  Peu satisfait(e)

4.  Pas du tout satisfait(e)

<h3>Satisfaction Gouvernement</h3>

Êtes-vous satisfait de la gouvernance actuelle dans votre pays ?

1.  Grandement satisfait

2.  Moyennement satisfait

3.  Peu satisfait

4.  Pas du tout satisfait

<h3>Institutions démocratiques</h3>

Quel est votre rapport avec les institutions démocratiques de votre pays
?

1.  J’y suis très attaché.e et je m’y intéresse beaucoup

2.  Je ne m’y intéresse que pour certaines politiques publiques

3.  Je ne m’y intéresse que très peu parce que je ne suis pas
    intéressé.e par a politique

4.  Je ne m’y intéresse pas du tout parce que je n’y crois plus

<h3>Vote - démonstration</h3>

Pour vous, voter est une démonstration de confiance envers l’élite
politique ?

1.  Oui, totalement

2.  Oui, mais de moins en moins

3.  Non, pas envers l’élite politique mais la démocratie seulement

4.  Non, cela n’a rien à voir

<h3>Confiance - Chef de l’État</h3>

Avez-vous confiance en votre chef d’État actuel ?

1.  Pas confiance

2.  Peu confiance

3.  Confiance

4.  Moyennement confiance

5.  Beaucoup confiance

<h3>Altruisme - politiques</h3>

Diriez-vous que les hommes politiques se préoccupent de ce que pensent
les gens comme vous ?

1.  Pas du tout

2.  Peu

3.  Moyennement

4.  Correctement

5.  Beaucoup

<h3>Education civique</h3>

J’ai appris mon rôle de citoyen grâce à l’enseignement civique que j’ai
reçu à l’école.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Ecoles</h3>

Les écoles devraient faire plus pour éduquer les jeunes sur les
avantages du vote et de la participation politique.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Compréhension - élites </h3>

Qu’ils soient de droite ou de gauche, ceux qui nous gouvernent ne
comprennent rien aux problèmes des individus comme nous.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Importance vote</h3>

Il est important de voter lors d’une élection.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Importance - représentation</h3>

Il est important que toute opinion soit représentée au Parlement

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Disproportion électorale</h3>

Il est inacceptable qu’un parti qui obtient moins de votes aux élections
obtienne le plus grand nombre de sièges.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Partis - votes</h3>

Les partis fédéraux (ou nationaux) sont pour la plupart seulement
intéressés par vos votes et non par vos opinions.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Votes - objectif</h3>

Dans mon pays, lors des dernières élections, les votes ont été
comptabilisés de façon objective.

<h3>Votes - délais</h3>

Dans mon pays, lors des dernières élections, les résultats ont été
annoncés dans un lapse de temps raisonnable.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Réédition de compte</h3>

Les élections sont un moyen de tenir le gouvernement responsable de ses
actes.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Importance - Chef</h3>

Sur un échelle de 0 à 10, où 0 veut dire “pas du tout important” et 10
veut dire “très important”, quelle importance accordez-vous aux chefs de
parti quand vous décidez pour quel parti voter ?

<h3>Intérêt politique</h3>

Sur une échelle de 0 à 10 (0 étant le plus faible et 10 le plus élevé)
comment évaluez-vous votre niveau d’intérêt pour la politique ?

<h3>Intérêt - politique US</h3>

Quelle attention accordez-vous à la politique américaine ?

1.  Très intéressé

2.  intéressé

3.  indifférent

4.  peu intéressé

5.  désintéressé

<h3>Connaissances - politique US</h3>

Sur une échelle de 0 à 10, notez le niveau de connaissance que vous
pensez avoir de la politique américaine (0 étant aucune connaissance et
10 étant beaucoup de connaissances)

<h3>Engagement politique</h3>

Quel mode d’engagement politique à votre préférence ?

1.  Le vote

2.  Manifestation et pétitions

3.  Manifestation, pétitions et vote

4.  Aucun

5.  Pas sûr

<h3>Proche parti</h3>

De façon générale, vous sentez-vous proche d’un parti politique ?

1.  Oui

2.  Non

3.  Ne sais pas

<h3>Importance traits</h3>

Sur une échelle de 0 à 10, à quel point considérez-vous le caractère
d’un candidat lorsque vous votez ? 0 = Pas du tout important; 10 = très
important

<h3>Traits de personnalité (plusieurs variables)</h3>

Classez les traits de personnalité d’un chef de parti du plus important
au moins important: intégrité, leadership, compétence, empathie.\

Note: une variable par trait.

-   trait\_integrite : rang integrite

-   trait\_leadership : rang leadership

-   trait\_competence : rang competence

-   trait\_empathie : rang empathie

<h3>Représentation - partis</h3>

Vous sentez-vous bien représentés par un des grands partis (plus de 5%
des voix aux dernières élections) de la scène fédérale ou nationale ? Si
le pays où vous votez utilise un système mixte ou entièrement
proportionnel, veuillez choisir “Ne s’applique pas”).

1.  Tout à fait

2.  De manière satisfaisante

3.  Pas vraiment

4.  Pas du tout

5.  Ne s’applique pas

<h3>Mode de scrutin</h3>

Quel est votre sentiment concernant votre mode de scrutin au niveau
fédéral ou national. Si le pays où vous votez utilise un système mixte
ou entièrement proportionnel, veuillez choisir “Ne s’applique pas”).

1.  Tout à fait satisfait

2.  Satisfait

3.  Neutre

4.  Peu satisfait

5.  Ne s’applique pas

<h3>Changement scrutin</h3>

Êtes-vous en faveur d’un changement de mode de scrutin incluant une
variable proportionnelle ? Cela implique une plus grande
proportionnalité entre les pourcentages de vote reçus des différentes
formations politiques et leurs pourcentages de sièges obtenus. Si le
pays où vous votez utilise déjà un mode de scrutin de type mixte ou
proportionnel, alors choisissez l’option “ne s’applique pas”.

1.  Tout à fait en faveur

2.  Plutôt en faveur

3.  Sans opinion, neutre

4.  Plutôt en défaveur

5.  Tout à fait en défaveur

6.  Ne s’applique pas

<h3>Vote stratégique</h3>

Si vous deviez juger du caractère démocratique du vote stratégique,
quelle serait votre évaluation sur une échelle de 0 à 10, 0 signifiant
un caractère anti-démocratique, 10, entièrement démocratique.

<h3>Intégration localité</h3>

Sur une échelle de 0 à 10 (0 étant pas du tout intégré et 10 étant
totalement intégré) comment qualifieriez-vous votre degré d’intégration
à votre province ou pays de résidence actuel ?

<h3>Thermometer - partis (plusieurs variables)</h3>

Sur une échelle allant de 0 à 10 (0=je déteste profondément ce parti,
10=j’adore profondément ce parti, 5=neutre), donnez un score aux partis
suivants: (note: une variable par parti, portant le nom du parti:
parti\_liberal, parti\_conservateur, ndp, bloc\_quebecois, parti\_vert)\

1.  Le Parti libéral

2.  Le Parti conservateur

3.  NDP

4.  Bloc Québécois

5.  Le Parti vert

## Information

<h3>Sources d’information</h3>

Quelle est votre principale source d’information politique ?

1.  La télévision

2.  Les réseaux sociaux

3.  Les journaux

4.  Les articles internet

<h3>Réseaux sociaux - cause</h3>

Avez vous déjà utilisé les réseaux sociaux pour défendre une cause que
vous soutenez ?

1.  Oui, plusieurs fois

2.  Oui une fois

3.  Non

4.  Je n’utilise pas les réseaux sociaux

<h3>Médias traditionnels</h3>

En période électorale, dans quelle mesure vous informez-vous dans les
médias traditionnels afin de prendre connaissance et de comprendre les
enjeux importants ?

1.  Beaucoup

2.  Assez

3.  Peu

4.  Pas du tout

<h3>Consultation sondage - 1</h3>

Avez-vous, récemment,consulté un sondage d’opinion, que ce soit sur
internet ou dans tout autre média (journaux, radio, télévision) ?

1.  Oui

2.  Non

3.  Ne sais pas

<h3>Consultation sondage (Canada / France)</h3>

[Si oui à la question précédente] Quel parti était en tête dans ces
sondages ?\

Canada:

1.  Parti Libéral

2.  Parti conservateur

3.  NDP

4.  Bloc Québécois

5.  Parti vert

France:\

1.  Le Parti socialiste

2.  La République en Marche

3.  Les Républicains

4.  La France insoumise

5.  Europe-Écologie - Les Verts

6.  Le Rassemblement national

<h3>Principale source</h3>

Quelle est votre principale source d’information lors des élections ?

1.  Amis

2.  Famille

3.  Réseaux sociaux: Facebook, Instagram, Twitter

4.  Journaux en ligne-Journaux papier

<h3>Engagement - réseaux sociaux</h3>

Vous sentez-vous plus engagé(e) politiquement depuis l’arrivée des
réseaux sociaux ?

1.  Oui

2.  Un peu

3.  Pas du tout

<h3>Abonnements - personnalités </h3>

Suivez-vous des personnalités politiques et\_ou médiatiques sur les
réseaux sociaux ?

1.  Oui, ceux qui partagent mes opinions politiques

2.  Oui de tout bords politiques

3.  Non

<h3>Fréquence utilisation</h3>

À quelle fréquence utilisez-vous les réseaux sociaux ?

1.  Jamais

2.  Rarement

3.  Plusieurs fois par semaine

4.  Moins d’une heure par jour

5.  Entre 1 et 2 heures par jour

6.  Entre 2 et 3 heures par jour

7.  Plus de 3 heures par jour

<h3>Inscriptions réseaux sociaux</h3>

À combien de réseaux sociaux êtes vous inscrits ?

1.  1

2.  2

3.  3

4.  4 ou plus

<h3>Contact - information</h3>

À quelle fréquence êtes vous en contact avec du contenu politique sur
les réseaux sociaux ?

1.  Jamais

2.  Rarement

3.  Souvent

4.  Systématiquement

<h3>Plateforme</h3>

Sur quelle plateforme voyez-vous passer le plus de contenu politique ?

1.  Twitter

2.  Youtube

3.  Facebook

4.  Autre

<h3>Couverture - influence</h3>

En période électorale, de quelle façon la couverture de différents
événements politiques comme des conférences de presse, des débats ou des
entrevues, influence-t-elle vote choix sur le bulletin de vote ?

1.  Beaucoup

2.  Assez

3.  Peu

4.  Pas du tout

<h3>Médias - neutralité</h3>

Les médias devraient toujours être neutre.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Biais médias</h3>

Les médias donnent une représentation de la société plus violente
qu’elle ne l’est réellement.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Chaînes - indépendance</h3>

Les chaînes de nouvelles canadiennes qui se présentent comme neutres et
indépendantes le sont réellement.

1.  Fortement d’accord

2.  Plutôt d’accord

3.  Ni en accord, ni en désaccord

4.  Assez en désaccord

5.  Plutôt en désaccord

6.  Fortement en désaccord

<h3>Niveau d’information</h3>

En général, comment évaluez-vous votre niveau d’information concernant
la politique :

1.  bien informé.e

2.  plutôt informé.e

3.  pas très informé.e

4.  pas du tout informé.e

5.  Je ne sais pas

<h3>Effet - débats</h3>

Indiquez sur une échelle de 0 à 10 à quel point le plus récent débat
télévisé que vous avez vu a changé vos opinions sur les candidats (0 pas
du tout 10 beaucoup)

<h3>Importance débats TV</h3>

Indiquez sur une échelle de 0 à 10 à quel point vous trouvez important
qu’on diffuse des débats politiques à la télévision lors des campagnes
électorales. (1= Pas du tout important; 10 = Très important)

<h3>Confiance contenus RS</h3>

À quel point faites vous confiance au contenu politique disponible sur
les réseaux sociaux ?

1.  Pas confiance

2.  Un peu confiance

3.  Moyennement confiance

4.  Beaucoup confiance

5.  Totalement confiance

<h3>Confiance - TV et Radio</h3>

À quel point faites-vous confiance au contenu politique diffusé à la
télévision, dans la presse écrite et à la radio ?

1.  Pas confiance

2.  Un peu confiance

3.  Moyennement confiance

4.  Beaucoup confiance

5.  Totalement confiance

<h3>Confiance - Presse écrite</h3>

À quel point faites-vous confiance au contenu politique diffusé dans la
presse écrite ?

1.  Pas confiance

2.  Un peu confiance

3.  Moyennement confiance

4.  Beaucoup confiance

5.  Totalement confiance

<h3>Site - parti </h3>

Répondez par oui ou par non si vous déjà : Accédé à un site internet
d’un parti ou d’un candidat

1.  Oui

2.  Incertain

3.  Non

<h3>Like - parti</h3>

Répondez par oui ou par non si vous déjà : s’être inscrit comme “soutien
- amis - followers ” d’un parti ou d’un candidat sur leur site internet

1.  Oui

2.  Incertain

3.  Non

<h3>Sophistication - Etats-Unis</h3>

Quel est le nom du ou de la juge que le président des États-Unis, Donald
Trump souhaite nommer à la Cour suprême des Etats-Unis avant l’élection
présidentielle de novembre 2020 ? Les répondant.e.s ayant trouvé la
bonne réponse (Amy Coney Barrett) sont codé.e.s 1, sinon 0.

1.  Morris Fiorina

2.  Amy Coney Barrett

3.  Ruth Bader Ginsburg

4.  Brett Michael Kavanaugh

<h3>Sophistication - [Freeland/Legault/macron/Pence/Singh]</h3>

Identifiez quelle position occupent les personnalités suivantes :

1.  Chrystia Freeland (bonne reponse: 5)

2.  François Legault (bonne reponse: 4)

3.  Emmanuel Macron (bonne reponse: 2)

4.  Mike Pence (bonne reponse: 3)

5.  Jagmeet Singh (bonne reponse: 1)

Note: 5 variables (sophistication\_freeland, sophistication\_legault,
sophistication\_macron, sophistication\_pence, sophistication\_singh).
Pour chacune, les répondant.e.s ayant trouvé la bonne réponse sont
codé.e.s 1, sinon 0.

## Vote

<h3>Participation</h3>

Pensez-vous voter aux prochaines élections ?

1.  Oui

2.  Non

<h3>Québec 2018</h3>

Pour quel parti aviez-vous voté lors des élections provinciales du
Québec en 2018 ?

1.  Coalition Avenir Québec

2.  Parti Québécois

3.  Parti Libéral du Québec

4.  Québec Solidaire

5.  Parti vert du Québec

6.  Autre

7.  Bulletin nul

8.  Je n’ai pas voté

Note: 8 variables (vote\_quebec2018\_CAQ, vote\_quebec2018\_PQ,
vote\_quebec2018\_PLQ, vote\_quebec2018\_QS, vote\_quebec2018\_vert,
vote\_quebec2018\_autre, vote\_quebec2018\_bulletinnul,
vote\_quebec2018\_pasvote). Pour chacune, les répondant.e.s ayant
indiqué avoir voté pour ce parti sont codé.e.s 1, sinon 0.

<h3>Vote - US</h3>

Si vous étiez un résident des États-Unis, pour quel parti voteriez-vous
?

1.  Pour le parti républicain

2.  Pour le parti démocrate

<h3>Vote habitude</h3>

Allez-vous voter à chaque élection ?

1.  Oui, je vote toujours

2.  Non, mais je vote la plupart du temps

3.  Non, mais j’ai déjà voté

4.  Non, je ne vote jamais

<h3>Vote - même parti</h3>

Avez-vous toujours voté pour le même parti au fil des années ?

1.  Oui

2.  Non

<h3>Intention de vote - France</h3>

(Si Français) Parmi les partis suivants, lequel a votre préférence si
l’élection présidentielle avait lieu cette semaine ? 

1.  La République en marche

2.  Les Républicains

3.  Europe Écologie - Les Verts

4.  Le Parti socialiste

5.  Le Rassemblement national

6.  La France insoumise

Note: 6 variables (vote\_france\_enmarche, vote\_france\_republicains,
vote\_france\_verts, vote\_france\_PS, vote\_france\_RN,
vote\_france\_insoumise). Pour chacune, les répondant.e.s ayant indiqué
avoir l’intention de voter pour ce parti sont codé.e.s 1, sinon 0.

<h3>Intention de vote - Canada</h3>

Si la prochaine élection fédérale avait lieu dans une semaine, quel
parti seriez vous plutôt en faveur d’appuyer ?

1.  Parti Libéral

2.  Parti conservateur

3.  NPD

4.  Bloc Québécois

5.  Le Parti Vert

6.  Autre

Note: 6 variables (vote\_canada\_liberal, vote\_canada\_conservateur,
vote\_canada\_npd, vote\_canada\_bloc, vote\_canada\_vert,
vote\_canada\_autre). Pour chacune, les répondant.e.s ayant indiqué
avoir l’intention de voter pour ce parti sont codé.e.s 1, sinon 0.

<h3>Intention de vote - Québec</h3>

Pour quel parti pensez-vous voter lors des futures élections
provinciales ?

1.  Coalition Avenir Québec

2.  Parti Québécois

3.  Parti Libéral du Québec

4.  Québec Solidaire

5.  Parti vert du Québec

6.  Autre

Note: 6 variables (vote\_quebec\_CAQ, vote\_quebec\_PQ,
vote\_quebec\_PLQ, vote\_quebec\_QS, vote\_quebec\_vert,
vote\_quebec\_autre). Pour chacune, les répondant.e.s ayant indiqué
avoir l’intention de voter pour ce parti sont codé.e.s 1, sinon 0.

<h3>Vote - Anciens présidents</h3>

(Si Français) Lequel des ces anciens présidents Français pourriez-vous
soutenir s’il se représentait à nouveau ? 

1.  Charles De Gaulle

2.  Jacques Chirac

3.  Nicolas Sarkozy

4.  François Hollande

5.  Emmanuel Macron

<h3>Vote - nationaliste</h3>

Sur une échelle de 0 à 10 (0 étant pas du tout probable et 10 étant
certain) quelle est la probabilité que vous votiez pour des partis
nationalistes, régionalistes ou indépendantistes québécois ?

<h3>Aucune preference</h3>

Imaginez que vous n’éprouvez aucune préférence pour les candidats et
pour aucun des partis. Que feriez-vous le jour de l’élection ?

1.  Choisir l’option la moins pire

2.  Voter au hasard

3.  Ne pas voter

<h3>Préférence - parti</h3>

Imaginez maintenant que vous avez une préférence pour un parti, mais que
vous n’aimez pas le candidat de ce parti. Que feriez-vous ?

1.  vote pour ce parti quand-même

2.  vote pour le parti adverse espérant passer un message

3.  ne vote pas

<h3>Satisfaction mode de scrutin</h3>

Quel est votre niveau de satisfaction avec le mode de scrutin actuel
dans votre pays ?

1.  Tout à fait satisfait

2.  Satisfait

3.  Ni satisfait, ni insatisfait

4.  Pas satisfait

5.  Pas du tout satisfait

<h3>Vote - chance favoris</h3>

Quelle phrase correspond le mieux à ce que vous feriez si vous estimez
que votre parti favori a peu ou pas de chance d’être représenté au
Parlement ?

1.  J’irai certainement voter

2.  J’irai probablement voter

3.  Je ne sais pas si je voterai ou non

4.  Je n’irai probablement pas voter

5.  Je n’irai certainement pas voter

<h3>Importance - compétence</h3>

Sur une échelle de 0 à 10, à quel point considérez-vous le niveau de
compétence d’un candidat lorsque vous votez ? 0 = Pas du tout important;
10 = très important

<h3>Motivation</h3>

Lorsqu’il s’agit de définir votre choix de vote, est ce l’idéologie qui
dicte votre choix ou bien la personnalité du candidat ?

1.  L’idéologie

2.  Le candidat

3.  Ni l’un, ni l’autre

<h3>Vote - premier choix</h3>

Lors de la dernière élection dans votre pays, aviez-vous voté pour le
parti de votre premier choix ?

1.  Oui

2.  Non

3.  Ne sais pas

<h3>Stratégie vote 2</h3>

[Si “non” question précédente] Avez-vous ressenti le besoin de voter
pour un parti qui ne représentait pas parfaitement vos valeurs afin de
réduire les chances d’un parti encore plus éloigné de vos valeurs de
remporter l’élection ?

1.  Oui

2.  Non

3.  Ne sais pas

<h3>Autre choix - fréquence</h3>

À quel fréquence considérez-vous voter pour un candidat ou un parti
politique qui n’est pas votre premier choix ?

1.  Toutes les élections

2.  Une élection sur deux

3.  Une élection sur trois

4.  Une Une élection sur quatre ou plus

5.  À aucune élection, je vote toujours pour mon premier choix

<h3>Refus vote - Canada</h3>

[Si répondant réside au canada] Y-a-t’il un parti fédéral parmi les
choix suivants pour lequel vous ne voterez jamais ?

1.  Parti Liberal

2.  Parti conservateur

3.  NPD

4.  Bloc Québécois

5.  Parti vert

6.  Non, aucun

<h3>Refus de voter pour un parti spécifique - France</h3>

[Si répondant réside en France] Y-a-t’il un parti parmi les choix
suivants pour lequel vous ne voterez jamais ?

1.  Le Parti socialiste

2.  La République en Marche

3.  Les Républicains

4.  La France insoumise

5.  Europe-Écologie - Les Verts

6.  Le Rassemblement national

7.  Non, aucun


