---
title: "test-xtable"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelsummary)
```

```{r}
d <- read.csv("data/sondage_recoded.csv") %>% dplyr::select(-X)

# categorical variables - 101 variables
categorical_variables <- c("Emploi" = 3, 
                           "Revenu" = 4,
                           "Genre" = 5,
                           "Citoyenneté" = 6,
                           "Ethnie" = 7,
                           "Éducation" = 9,
                           "Religion" = 10,
                           "Réseau social" = 11,
                           "Résidence" = 12,
                           "Province" = 16, 
                           "Classe sociale" = 18,
                           "Résidence parents - province" = 21,
                           "Residence parents - pays" = 22,
                           "Climat social" = 23,
                           "Covid - satisfaction" = 24,
                           "Covid - gestion" = 26,
                           "Covid - jeunes" = 28,
                           "Covid - politiques" = 29,
                           "Immigration - ouverture" = 30, 
                           "Immigration - Syrie" = 31,
                           "Climat - économie" = 32,
                           "Transition énergétique - taxes" = 33,
                           "Climat - impacts" = 34,
                           "Confiance - police" = 35,
                           "Sécurité - quartier" = 36,
                           "Sécurité - gouvernement" = 37,
                           "Sécurité - immigration" = 38,
                           "Sécurité - frontières" = 39, 
                           "Immigration - quotas" = 40,
                           "Mninorités - partis" = 41,
                           "Corruption" = 42,
                           "Mondialisation" = 45,
                           "Économie - évaluation sociotropique" = 46,
                           "Économie - évaluation égotropique" = 47,
                           "Économie - statisfaction" = 48,
                           "Économie - préoccupation" = 49,
                           "Économie - critères" = 50, 
                           "Économie - confiance (Canada)" = 51,
                           "Économie - confiance (France)" = 52,
                           "Immigration - confiance (Canada)" = 53,
                           "Immigration - confiance (France)" = 54,
                           "Représentation des minorités" = 56,
                           "Importance - écologie" = 64,
                           "Inquiétude - attentats" = 65,
                           "Satisfaction envers la démocratie" = 67,
                           "Satisfaction Gouvernement" = 68, 
                           "Institutions démocratiques" = 69,
                           "Vote - démonstration" = 70,
                           "Confiance - Chef de l'État" = 71,
                           "Altruisme - politiques" = 72,
                           "Education civique" = 73,
                           "Écoles" = 74,
                           "Compréhension - élites" = 75,
                           "Importance vote" = 76,
                           "Importance - représentation" = 77, 
                           "Disproportion électorale" = 78,
                           "Partis - vote" = 79,
                           "Votes - objectif" = 80,
                           "Vote - délais" = 81,
                           "Réédition de comptes" = 82,
                           "Intérêt - politique US" = 85,
                           "Engagement politique" = 87,
                           "Proche parti" = 88,
                           "Représentation = partis" = 94, 
                           "Mode de scrutin" = 95,
                           "Changement scrutin" = 96,
                           "Sources d'information" = 104,
                           "Réseaux sociaux - cause" = 105,
                           "Médias traditionnels" = 106,
                           "Consultation sondage - 1" = 107,
                           "Consultation sondage 2 - Canada" = 108,
                           "Consultation sondage 2 - France" = 109,
                           "Principale source" = 110, 
                           "Engagement - réseaux sociaux" = 111,
                           "Abonnements - personnalités" = 112,
                           "Fréquence utilisation" = 113,
                           "Contact - information" = 115,
                           "Plateforme" = 116,
                           "Couverture - influence" = 117,
                           "Médias - neutralité" = 118,
                           "Influence des médias sur l'élection" = 119,
                           "Biais médias" = 120, 
                           "Chaînes - indépendance" = 121,
                           "Niveau d'information" = 122,
                           "Confiance contenu RS" = 125,
                           "Confiance - TV et radio" = 126,
                           "Confiance - presse écrite" = 127,
                           "Site - parti" = 128,
                           "Like - parti" = 129,
                           "Vote habitude" = 146,
                           "Vote - anciens présidents" = 166, 
                           "Aucune préférence" = 168,
                           "Préférence - parti" = 169,
                           "Satisfaction mode de scrutin" = 170,
                           "Vote - chance favoris" = 171,
                           "Motivation" = 173,
                           "Vote - premier choix" = 174,
                           "Stratégie - vote 2" = 175,
                           "Autre choix - fréquence" = 176, 
                           "Refus de voter pour un parti - Canada" = 177,
                           "Refus de voter pour un parti - France" = 178)

# dichotomous varibales - 44 variables
dichotomous_variables <- c("Minorité" = 8, 
                           "Naissance pays résidence" = 13,
                           "Cohabitation" = 14,
                           "Droit de vote" = 15,
                           "Né.e dans votre province de résidence" = 17,
                           "Classe sociale - parents" = 19,
                           "Langue" = 20,
                           "Covid - accès aux soins" = 25,
                           "Déficit" = 55,
                           "Sophistication - États-Unis" = 130, 
                           "Sophistication - Freeland" = 131,
                           "Sophistication - Legault" = 132,
                           "Sophistication - Macron" = 133,
                           "Sophistication - Pence" = 134,
                           "Sophistication - Singh" = 135,
                           "Participation" = 136,
                           "Québec 2018 - CAQ" = 137,
                           "Québec 2018 - PQ" = 138,
                           "Québec 2018 - PLQ" = 139, 
                           "Québec 2018 - QS" = 140,
                           "Québec 2018 - PVQ" = 141,
                           "Québec 2018 - Autre" = 142,
                           "Québec 2018 - Bulletin nul" = 143,
                           "Québec 2018 - Pas voté" = 144,
                           "Vote - US" = 145,
                           "Vote - même parti" = 147,
                           "Intention de vote France - République en marche" = 148,
                           "Intention de vote France - Républicains" = 149, 
                           "Intention de vote France - Verts" = 150,
                           "Intention de vote France - PS" = 151,
                           "Intention de vote France - RN" = 152,
                           "Intention de vote France - France insoumise" = 153,
                           "Intention de vote Canada - Libéral" = 154,
                           "Intention de vote Canada - Conservateur" = 155,
                           "Intention de vote Canada - NPD" = 156,
                           "Intention de vote Canada - Bloc" = 157,
                           "Intention de vote Canada - Vert" = 158,
                           "Intention de vote Canada - Autre" = 159,
                           "Intention de vote Québec - CAQ" = 160,
                           "Intention de vote Québec - PQ" = 161,
                           "Intention de vote Québec - PLQ" = 162,
                           "Intention de vote Québec - QS" = 163,
                           "Intention de vote Québec - PVQ" = 164,
                           "Intention de vote Québec - Autre" = 165)

# continuous variables - 32 variables
continuous_variables <- c("Année de naissance" = 1, 
                          "Âge" = 2,
                          "Covid - inquiétude" = 27, 
                          "Corruption - participation" = 43,
                          "Corruption - évaluation des partis" = 44, 
                          "Enjeux - chômage" = 57,
                          "Enjeux - environnement" = 58, 
                          "Enjeux - immigration" = 59,
                          "Enjeux - économie" = 60, 
                          "Enjeux - éducation" = 61,
                          "Enjeux - santé" = 62,
                          "Importance - immigration" = 63,
                          "Idéologie" = 66,
                          "Importance - chef" = 83, 
                          "Intérêt politique" = 84,
                          "Connaissances - politique US" = 86, 
                          "Importance traits" = 89,
                          "Traits - importance - intégrité" = 90, 
                          "Traits - importance - leadership" = 91,
                          "Traits - importance - compétence" = 92, 
                          "Traits - importance - empathie" = 93,
                          "Vote parti nationaliste" = 97, 
                          "Intégration localité" = 98,
                          "Thermomètre partis - Libéral" = 99, 
                          "Thermomètre partis - Conservateur" = 100,
                          "Thermomètre partis - NPD" = 101, 
                          "Thermomètre partis - Bloc" = 102,
                          "Thermomètre partis - Parti vert" = 103, 
                          "Inscription réseaux sociaux" = 114,
                          "Effet - débats" = 123, 
                          "Importance débats TV" = 124,
                          "Vote stratégique" = 167,
                          "Importance compétence" = 172)

# categorical and dichotomous variables (for cross tabs)
cat_dicho_variables <- c(categorical_variables,  dichotomous_variables)

# dependent variables only (dichotomous or continuous)
dependent_variables <- c(continuous_variables, dichotomous_variables)

# all variables
variables <- c(categorical_variables, dichotomous_variables, continuous_variables)

# chanhe class of categorical and dichotomous variables
d[cat_dicho_variables] <- sapply(d[cat_dicho_variables], as.factor)

#as.data.frame.matrix(table(d[, as.numeric(input$var1)], d[, as.numeric(input$var2)], useNA = "always")), rownames = T
test <- table(d$revenu, d$ethnie, useNA = "always")
summary(d$revenu)

datasummary(genre ~  ethnie + (Pourcentage = Percent()),
            data = d)

datasummary(genre * ethnie + 1 ~ (`Nombre d'observations` = 1) + (`Pourcentage` = Percent()),
            data = d)




# y <- d[, as.numeric(input$var1)]
# x <- d[, as.numeric(input$var2)]
#     
#     datasummary(d[, as.numeric(input$var1)] * d[, as.numeric(input$var2)] + 1 ~ (`Nombre d'observations` = 1) + (`Pourcentage` = Percent()),
#                 data = d)
```
